### ISSUE TITLE
`i18n-embed` does not compile with Rust 1.92.0

### ISSUE THREAD

**Issue by fosskers** [kellpossible/cargo-i18n#164]
The error shown is this:
```
error[E0310]: the associated type `impl Iterator<Item = Cow<'static, str>>` may not live long enough
  --> i18n-embed/src/assets.rs:44:9
   |
44 |         Box::new(Self::iter().map(|filename| filename.to_string()))
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |         |
   |         the associated type `impl Iterator<Item = Cow<'static, str>>` must be valid for the static lifetime...
   |         ...so that the type `impl Iterator<Item = Cow<'static, str>>` will meet its required lifetime bounds
```
within [this function](https://github.com/kellpossible/cargo-i18n/blob/master/i18n-embed/src/assets.rs#L43-L45). At first glance I'm not sure what the real issue is, or why this suddenly broke.

**Comment by francisdb** [comment]
I also wonder where this comes from, going back to older rust versions does not fix this.

**Comment by SimonHeidrich** [comment]
I strongly suspect that this has to do with version 8.10.0 of [rust-embed](https://docs.rs/rust-embed/latest/rust_embed/), [rust-embed-impl](https://docs.rs/rust-embed-impl/latest/rust_embed_impl/) or [rust-embed-utils](https://docs.rs/rust-embed-utils/latest/rust_embed_utils/), which got released yesterday.

Their repository is rather private, though: https://pyrossh.dev/repos/rust-embed
No GitHub issues to open there.

Does anyone know the maintainers? 😄

**Comment by francisdb** [comment]
> Does anyone know the maintainers? 😄

Reported at https://groups.google.com/g/rust-embed-devs/c/fCfzNiYCaD8

**Comment by SimonHeidrich** [comment]
The author has reverted the changes with version 8.11.0, a `cargo update` fixed the compilation error for me.
https://groups.google.com/g/rust-embed-devs/c/fCfzNiYCaD8

**Comment by fosskers** [comment]
Confirmed, thanks guys!

**Comment by gemcoder21** [comment]
@fosskers do you think it make sense to bring/fork `rust-embed` from https://pyrossh.dev/repos/rust-embed ` GitHub? it makes it hard to audit the code

**Comment by fosskers** [comment]
Probably not. Forking (or even mirroring) means you have to maintain it forever.
