### PR TITLE
fix: fix `i18n-embed` build with `rust-embed 8.10`

### LINKED ISSUE #164: `i18n-embed` does not compile with Rust 1.92.0
The error shown is this:
```
error[E0310]: the associated type `impl Iterator<Item = Cow<'static, str>>` may not live long enough
  --> i18n-embed/src/assets.rs:44:9
   |
44 |         Box::new(Self::iter().map(|filename| filename.to_string()))
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |         |
   |         the associated type `impl Iterator<Item = Cow<'static, str>>` must be valid for the static lifetime...
   |         ...so that the type `impl Iterator<Item = Cow<'static, str>>` will meet its required lifetime bounds
```
within [this function](https://github.com/kellpossible/cargo-i18n/blob/master/i18n-embed/src/assets.rs#L43-L45). At first glance I'm not sure what the real issue is, or why this suddenly broke.

### PR DESCRIPTION
**Pull request by eatradish**
fix #164

### CODE REVIEW

**Comment by francisdb** [comment]
This has been [fixed upstream](https://github.com/kellpossible/cargo-i18n/issues/164#issuecomment-3750272258). Think this can be closed.
